name: Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare env 
        run: |
          sudo apt update && sudo apt install -y ccache 

        shell: bash
      - name: Checkout latest code
        uses: actions/checkout@v4.1.1
        with:
          clean: true
          fetch-depth: 0
          fetch-tags: true
      - name: Build
        run: |
          ./build.sh
          ls
          pwd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-Artifacts
          path: Uvite*.zip
